### ISSUE TITLE
Missing dependencies on install

### ISSUE THREAD

**Issue by dotnetCarpenter** [atom-haskell/ide-haskell#105]
```
apm --version
apm  1.0.4
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.1.4
```
![haskell_ide_error](https://cloud.githubusercontent.com/assets/43763/9989728/4a33e95a-605b-11e5-951b-b5ff9cbec20d.png)

1. Haskell-ghc-mod: ghc-mod failed to launch it is probably missing or misconfigured
  1. Error: spawnSync ghc-mod ENOENT
2. Haskell-ghc-mod: ghc-mod lang failed with error message Error: spawn ghc-mod ENOENT
3. Haskell-ghc-mod: ghc-mod flag failed with error message Error: spawn ghc-mod ENOENT

**Comment by kRITZCREEK** [comment]
it looks like you didn't install ghc-mod. Do you have [ghc.mod](http://www.mew.org/~kazu/proj/ghc-mod/en/) on your path?

**Comment by dotnetCarpenter** [comment]
Unfortunately, I'm most of the time offline and just limited time online. Would be nice if the package installed or warned about the dependencies on install. That aside, I now got `ghc-mod` installed and get the following error when I save a `.hs` file:

```
Haskell-ghc-mod: ghc-mod lint /home/dotnet/projects/playground/haskell1/ch02/baby.hs failed with error code 1
ghc-mod: Couldn't find file: HLint
Tried with:
  HLint
  HLint.hs
  /usr/share/hlint/HLint
  /usr/share/hlint/HLint.hs
```
After a quick search I found [HLint](https://hackage.haskell.org/package/hlint) and will install it.
Isn't there anyway that `atom-haskell` can install it's dependencies?

**Comment by dotnetCarpenter** [comment]
Hmm just installed `HLint` via cabal but I'm still getting the error. I'm new to the Haskell eco-system. Where do I check if `HLint` is installed correctly or if this is a `ide-haskell` bug?

**Comment by lierdakil** [comment]
Hlint is a ghc-mod dependency, and as such should be generally installed with ghc-mod. If you've got yourself some weird pre-built ghc-mod package that lacks hlint, I can only advise you to put `$HOME/.cabal/bin` into your PATH (or 'additional path directories' option for haskell-ghc-mod) and hope for the best. If possible, I'd advise you to install ghc-mod via cabal, which should pull and link hlint automatically.

Dependencies are listed in `haskell-ghc-mod` package readme, and I find 'ENOENT' error is quite self-explainatory for most developers, since it's a standard file-not-found error code.

Sadly, due to sheer number of possible configurations, it's not a very good idea to try to install an environment automatically -- it would likely create more problems than it would solve.

**Comment by dotnetCarpenter** [comment]
So you say that doing a check for cabal and install the dependencies via cabal is a bad idea?
I did do `apm install language-haskell haskell-ghc-mod ide-haskell autocomplete-haskell` but I got the errors anyhow and needed to do `cabal update && cabal install ghc-mod hlint` before they went away.

Since my issue is resolve I'm gonna close this. Thanks for the feedback.

**Comment by telephon** [comment]
For the record: The same problem in a (perhaps) slightly different setting could be solved by:

````
cabal update
cabal install happy
cabal install haskell-src-exts-1.16.0.1
````

**Comment by lierdakil** [comment]
Please file a new issue if you need help, and describe your setup and what
is going wrong.
15 окт. 2015 г. 15:19 пользователь "Julian Rohrhuber" <
notifications@github.com> написал:

**Comment by fmiguellopez** [comment]
There is no need for patches or path modifications.

1. Install (if you haven't done so yet) ghc-mod and ghc-modi. You can do this through https://ghcformacosx.github.io or using command line with cabal.
2. execute "which ghc-mod" and "which ghc-modi" in command line.
3. Copy and paste both paths on your settings path for both ghc-mod and ghc-modi in haskell-ghc-mod package in atom.

**Comment by telephon** [comment]
Thank you for the directions, I'm sure others will find them useful, too.

1.

```ghc-modi``` seems not to exist in cabal, I get:
```
cabal install ghc-modi
cabal: There is no package named 'ghc-modi'.
You may need to run 'cabal update' to get the latest list of available
packages.
```

2. 

```which ghc-mod``` returns nothing. So it seems not to be installed. By contrast, 
```cabal install ghc-mod``` returns
```All the requested packages are already installed:
ghc-mod-5.4.0.0
```

**Comment by fmiguellopez** [comment]
I believe ghc-mod is installed together with ghc-mod, and most probably which ghc-mod returns nothing because it's path has not been added to $PATH.

I still had the ghc-mod NOENT problem when I had ghc-mod paths exported, so I was asuming this step. 

Nevertheless 'which' command is just to see path, which you can now depending on how you installed ghc-mod. Homebrew installs it on your home ~/.cabal, https://ghcformacosx.github.io locates it in its own package. I don't know about macports...

In settings for Haskell-ghc-mod just type in locations for ghc-mod (mine is "/Users/Miguel/.cabal/bin/ghc-mod") and same for ghc-modi (with it's 'i').

**Comment by AsymLabs** [comment]
Exactly same problem here :

Linux 3.13.0-24-generic #47-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
Atom 1.1.0
Node v0.10.33

$ which ghc-mod
/home/xxxx/.cabal/bin/ghc-mod

$ which ghc-modi
/home/xxxx/.cabal/bin/ghc-modi

**Comment by AsymLabs** [comment]
Problem solved.  Here's what worked for me, following steps 2 and 3 of fmiguellopez:

1. Edit -> Preferences -> Packages
2. Find package **haskell-ghc-mod** -> Settings
3. Scroll down to Ghc-Mod Path -> copy and paste result of `which ghc-mod`
4, Scroll down to Ghc-Modi Path -> copy and paste result of `which ghc-modi`
5. Tick `Enable Ghc Modi`
6. Now close ALL tabs/files *
7. Restart atom and open Haskell file.  It should work.

* otherwise another ghc-mod error may be displayed on restarting - this is what happened to me.

Also it appears that ghc-modi is installed along with ghc-mod by default, there does not appear to be a  separate ghc-modi package.

**Comment by telephon** [comment]
This procedure works here  too, with cabal installed from homebrew on OS X 10.11. Thanks!
