### ISSUE TITLE
a stack-based backend

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell#108]
i.e. ide-haskell-stack to use stack build tool as a backend for testing and building etc. as an alternative to ide-haskell-cabal

**Comment by lucamolteni** [comment]
+1

**Comment by cblp** [comment]
+1

**Comment by lierdakil** [comment]
This might take a while, due to severe lack of time, but if someone's willing to implement this based on `ide-haskell-cabal`, I'll be happy to include and endorse it.

**Comment by lucamolteni** [comment]
LIerdakil does ide-haskell use ide-haskell-cabal internally? I guess we'd need to create a ide-haskell-stack to use then

**Comment by wolftune** [comment]
@lucamolteni yes, we need to make an ide-haskell-stack — it would likely be similar to ide-haskell-cabal

**Comment by lucamolteni** [comment]
I'm taking a look at the source code, but ide-haskell-cabal seems a little different, since it helps you switching throughout different version of ghc, something that stack does by himself.

I guess a Stack build system could be easier, by simply executing cabal build (we could switch ghc with the .stack file)

**Comment by wolftune** [comment]
@lucamolteni yes, the stack stuff should let Stack do the GHC selection, but it should never use `cabal build` because it should be doing `stack build` instead…

**Comment by lucamolteni** [comment]
@wolftune yes, I agree. What I'm saying is that it should be easier than ide-haskell-cabal.

Anyway, are you using the ghc-mod integration with slack now right?

**Comment by wolftune** [comment]
I assume you mean "stack" ot "slack" and yes, I only use Stack, and ide-haskell *works* without the ide-haskell-cabal backend, it just shows a warning (that can be turned off), and the features that supports are not available.

**Comment by lucamolteni** [comment]
@wolftune Yeah I edited thanks.

Which feature you'd like to have in ide-haskell-stack implemented first?

**Comment by lierdakil** [comment]
@lucamolteni, you might want to take a look at #116. TL;DR I feel like I have to change API interface to keep it manageable. It's still some time until I release updated versions, but you might want to keep this in mind, if you're working on ide-haskell-stack.

You also can take a quick look at https://github.com/atom-haskell/ide-haskell-cabal/pull/5 to get a general idea of what changed.

Sorry for the inconvenience.

**Comment by wolftune** [comment]
@lucamolteni I'm not sure what these backends even do, i.e. what the cabal one does. I'm guessing it lets one do stuff like `cabal build` and `cabal test` from Atom maybe? If so, `stack build` and `stack test` make sense to support. I don't have any requests here, just in general wold like to see feature parity for stack projects.

**Comment by lierdakil** [comment]
Long story short, ide-haskell-cabal exposes build (optionally with a particular target), test and clean commands. Compilation errors and warnings are reported in pretty much the same way as ghc-mod check results.

**Comment by lucamolteni** [comment]
@lierdakil Thanks for the information, no problem about the API, I still don't know if I'm going to work on this feature or not. Since now I know that you're changing the API anyway, I'll probably wait, I'm personally fine with ghc-mod itself anyway, but I still want to know what other users may expect from this.

**Comment by lierdakil** [comment]
I probably should mention that new API is live. If interested, see https://github.com/atom-haskell/ide-haskell/blob/master/lib/upi.coffee for general overview and https://github.com/atom-haskell/ide-haskell-cabal/blob/master/lib/ide-haskell-cabal.coffee for usage example

**Comment by stefanscheidt** [comment]
+1 for a ide-haskell-stack

**Comment by huiwang** [comment]
an engine that tries to unify all https://github.com/haskell/haskell-ide-engine

**Comment by ches** [comment]
This may be somewhat of an aside, but while we're on the topic of multiple build backends and adding a new one… is it worth thinking about instead shipping providers for [the build package][] (and while we're at it, maybe [the linter package] instead of `ide-haskell`'s homegrown one)?

Perhaps this has been discussed elsewhere before, and maybe something like `ide-haskell-cabal` has a wider scope than what providers for the `build` package can do, but it might reduce the code that has to be maintained for `ide-haskell` and its backends, and personally I like the uniform user interface that these packages provide across work in different languages (consistent UI & consistent mappings without needing a bunch of scoped config overrides).

[the build package]: https://atom.io/packages/build
[the linter package]: https://atom.io/packages/linter

**Comment by lierdakil** [comment]
@ches, ide-haskell has a wider scope than that of linter. E.g. type/info tooltips are shown by ide-haskell as well. I only provide linter support for folks who don't want that extra functionality.
The same goes for build package. Granted, I'm not too familiar with it, but I don't think there is a way to report build errors the same way as I do now with ide-haskell. Besides, cabal has many more commands than just `build`. While I didn't implement `configure` and `install` yet (too much stuff on my hands at the moment), but I plan to eventually.
And while you are correct on the amount of code I have to maintain, there is a reason to prefer a home-grown solution: API changes. There is a big cognitive overhead of keeping up with those.

**Comment by nwolverson** [comment]
Having looked at these options for another package, the current ide-haskell display is better for large multiline errors than linter, and the configuration of the build package isn't ideal in some ways depending on your requirements. In my ideal world the general-purpose packages would provide more low-level ways to nicely "display a bunch of errors" (linter has added an api more like this) and "display a build pane" (build could maybe be extended this way). 

So ideally improvements could be pushed to those packages which would be useful for everyone, but I don't think it's there just now.

**Comment by lierdakil** [comment]
@nwolverson, just for reference, it was me who implemented multiline message support in linter. While implementation might be not ideal, I figured that keeping look-and-feel between single-line and multiline messages is important, hence that clunky 'click/press hotkey to expand' solution. I didn't follow linter development as of late, so I don't know if something's changed since though.

**Comment by ches** [comment]
> ide-haskell has a wider scope than that of linter. E.g. type/info tooltips are shown by ide-haskell as well. I only provide linter support for folks who don't want that extra functionality.

That's just it—personally, I *do* want the type hints and such that `ide-haskell` provides, but I'd rather not use its linter functionality. Is there a straightforward way to disable it? I don't see an exposed config setting. Sorry to stray off topic with the question.

More on topic, providers written for the `build` package can have flexibility to run much more than a `build` command. They will expose "targets" (which could specifically be the project's build targets, but also auxiliary tasks like `configure`) and then the user can quickly open a palette and run their choice of them. My point here, in reference to the subject of the ticket, is that `ide-haskell` would now probably be considering how to share code to do these things with two different tools, `cabal` and `stack`. There is already IMO a good abstraction layer for doing this in the community that many languages make use of.

Totally understand your concerns about the burden of dependencies and having to keep up with their breaking changes, though, so it's just a suggestion to consider. If you decide to stick to your own linter and build tool support, I just hope you'll make it simple to disable them, so users like me can use alternatives while still enjoying the other features of `ide-haskell` (like type lookups).

Thanks for your consideration!

**Comment by nwolverson** [comment]
@lierdakil It's not a criticism of linter, I can't say it's obvious to me how you might improve that incrementally - and I'm using this in [ide-purescript](http://github.com/nwolverson/atom-ide-purescript) to display similar sometimes very large messages - but I found the ide-haskell version slicker for those large messages.

**Comment by lierdakil** [comment]
@ches, I think originally, hgm didn't display error messages using ide-haskell if 'use linter' was enabled. I probably messed it up while fumbling around changing API. That said, you can disable 'Check/Lint on Save/Change' options. Those don't affect linter support. I will try to improve on linter support a bit when I get some time. If you could open a new issue on hgm repo, that would be appreciated, since I have a tendency to forget things lately -- too much stuff to keep track of.

@nwolverson, well, ide-haskell was designed with those large messages in mind, due to, well, Haskell's error messages often going Shakespeare on user, so that can be expected. Linter strives for generality though, and in most cases, error messages are relatively short.
This isn't meant to be an excuse, btw, I'm just trying to offer insight on some design decisions. So no offense taken and/or meant.

**Comment by lierdakil** [comment]
Finally, a stack build backend for ide-haskell is available. Functionality is pretty much bare-bones, and you can expect an occasional bug. But here it is: https://atom.io/packages/ide-haskell-stack. More than 80% of code base is carbon copy of `ide-haskell-cabal`. To this effect, I might consider merging these two back eventually. That being said, I'd like to see some real-world testing on this package. Feel free to file issues if something doesn't work as you expect it to.

**Comment by wolftune** [comment]
Works fine in my testing so far, no issues.

**Comment by polux** [comment]
Awesome, thanks!

**Comment by shmish111** [comment]
Hey guys, what happened to this, atom.io giving me a 404 and can't find it
