### ISSUE TITLE
0.8.0 infinite loop install

### ISSUE THREAD

**Issue by MarkZander** [atom-haskell/ide-haskell#115]
0.8.0 takes forever to update. If I uninstall and then hit install 0.7.1 is installed. Check updates sez that I need to update to 0.8.0.

Is there a way to find out why 0.8.0 seems to go into an infinite loop when updating so we can find out what's going wrong? Is there something setup incorrectly on my computer?

**Comment by lierdakil** [comment]
This problem is most likely not specific to ide-haskell.

First make sure you're using latest version of Atom (1.0.19 at the moment of writing)

If you are, I would assume Atom is somewhat borked. You might need to wipe `~/.atom` configuration dir to fix this (**back it up first, so that you can restore it in case wiping doesn't help!**)

Also bear in mind that in some cases, Atom seems to hang on updates for no apparent reason -- if you restart it, everything just works fine.

All in all, you have a better chance of getting help with this on [Atom's forums](https://discuss.atom.io/) or [slack](https://discuss.atom.io/t/join-us-on-slack/16638)

**Comment by MarkZander** [comment]
I did an uninstall and then reinstalled ide-haskell. That seemed to work.

Mark
