### ISSUE TITLE
Support building application with ghc --make

### ISSUE THREAD

**Issue by romildo** [atom-haskell/ide-haskell#150]
I intend to use Atom for developing very simple applications with my undergraduate students on Functional Programming. Most of them will be on single files. For that it is much easier to compile with `ghc --make` then with `cabal` (which needs an additional cabal file for each application).

Can `ghc --make` be supported for compilation?

**Comment by lierdakil** [comment]
We'd need to invent a project file format for that, since `ghc --make` needs at least main file, and one would probably want some incude/lib directories passed to it as well. Personally, I don't see much benefit in that, since there already is a project file format. Namely, cabal files.

Cabal is an integral part of Haskell ecosystem, and if I might, I'd suggest you include it in your course, if at all possible. If you don't want to introduce cabal right away (or at all for some reason), it should be possible to play around that by using repl (e.g. see ide-haskell-repl package), or you might just provide skeleton cabal files for your students.

If you're adamant that you just 'have to have it', I suppose I could slap a barebones implementation together. But frankly, don't expect much (or any) support for that configuration.
