### ISSUE TITLE
"module not found" in same folder

### ISSUE THREAD

**Issue by doodledood** [atom-haskell/ide-haskell#152]
when I try to import another module (any module) that resides in the same folder, Atom gives me an error "module not found" while import statements from the haskell core like Data.List do work.

Note: The files compile successfuly, just the ide gives an error

**Comment by lierdakil** [comment]
Do you use cabal/stack for project management, or is it a 'plain' project?

**Comment by doodledood** [comment]
Actually the issue got resolved as soon as I introduced stack and added the folder to the configuration file. 

It appears that the issue appears only when there is not project management tool involved like cabal/stack. 

Maybe "plain" projects should be supported

**Comment by lierdakil** [comment]
They are. Moreover, plain project module resolution works fine on my end (with having everything in the same directory)

So, either there is some weirdness in your environment, project, or you found a heisenbug -- probably in ghc-mod, although might be in root directory resolution code.

**Comment by doodledood** [comment]
I see. I forgot to mention that I am running Windows 10. It is probably related to that

**Comment by lierdakil** [comment]
Might be. Although I don't immediately see why. I do have a Windows 10 machine, so I might try investigating at some point. Might take a while though.

**Comment by michalczaplinski** [comment]
Hi, I seem to be having the same issue on Linux Mint when the imported module is in the same directory. Is there anything I could try to help troubleshoot it?

**Comment by lierdakil** [comment]
@michalczaplinski, a bit. I'd like to try to reproduce this on my end first. So if you could show directory structure (related to project root) and module name that fails to import, that'd be nice.

**Comment by michalczaplinski** [comment]
![snapshot](https://cloud.githubusercontent.com/assets/5417266/16339240/dcf0e8d8-3a21-11e6-924d-182502924ce9.png)

**Comment by michalczaplinski** [comment]
![image](https://cloud.githubusercontent.com/assets/5417266/16339652/1eab6e22-3a24-11e6-8b5b-0018ee71e554.png)

**Comment by lierdakil** [comment]
Okay. So problem is, it's quite literally impossible to determine root directory correctly in this case, because that depends entirely on ghc invocation directory. A generic fallback assumes that Atom project root is Haskell project root. But only you know what Haskell project root actually is.

So you have two options, basically. Either open directories `1`, `2` etc with Atom's 'Add Project Folder' (or by invoking Atom in actual root directory), or add an empty `.cabal` (literally, i.e. not `something.cabal`, just `.cabal`) to actual Haskell root directories (i.e. `1`, `2`, etc in this case).

Hope this helps.

**Comment by michalczaplinski** [comment]
Ah, I see. Yup, that solves it. Thanks!
