### ISSUE TITLE
Codex Integration

### ISSUE THREAD

**Issue by aloiscochard** [atom-haskell/ide-haskell#18]
Hi @chaika2013,

I'm the author of `codex` (http://github.com/aloiscochard/codex) and I was wondering if you have any plan to integrate it?

As that would solve the "jump to declaration" on your todo list!

I did not know about your project so I ask for: https://github.com/yongkangchen/atom-ctags/issues/21

But really, here is the place to continue the discussion.

Thanks

**Comment by lierdakil** [comment]
Thank you for your suggestion, but this project is somewhat ghc-mod centered. While I can't argue on behalf of @chaika2013, but atom-ctags seems like more suitable place for said integration, since using `codex` in ide-haskell would require a whole new tags parser mechanic (and add additional dependency as well), while ghc-mod itself is probably enough to implement jump-to-declaration.

**Comment by lierdakil** [comment]
Since backend is mostly delegated to `haskell-ghc-mod`, and autocompletion facilities to `autocomplete-haskell`, this issue is out-of-scope now. Feel free to reopen/comment if you still think said integration makes sense.
