### ISSUE TITLE
Ide-haskell doesn't want to start at all

### ISSUE THREAD

**Issue by YanaRGeorgieva** [atom-haskell/ide-haskell#187]
Hello. I've tried out this plugin on my 64bit laptop on the portable  version of Haskell and it worked perfectly, but on the 32bit tablet, even though I added all the paths to the binary for the other dependencies and so on, it just doesn't want to even start and emerge as a plugin in the command pallet.
Thanks in advance.

**Comment by lierdakil** [comment]
I don't really think bitness has much to do with it. I think Atom only recently got 64-bit version for Windows.

Some sanity checks:
1. Check if you have Atom v1.13. Earlier versions can (and some of those *will*) misbehave.
1. Make sure you have language-haskell installed
2. Try opening a Haskell file -- ide-haskell & friends don't start otherwise
3. Double-check that opened Haskell file uses Haskell grammar.
4. Make sure that you have no other Haskell grammar packages
5. Check developer console for errors.

**Comment by lierdakil** [comment]
Closing due to no response.
