### ISSUE TITLE
Use HIndent for prettify 

### ISSUE THREAD

**Issue by agbell** [atom-haskell/ide-haskell#20]
It would be great if hindent could be integrated:
https://github.com/chrisdone/hindent

**Comment by rvion** [comment]
I too wish this was in by default.

https://github.com/chrisdone/hindent:

 - sensible default baked in
 - an example atom integration code to copy-paste from: https://github.com/chrisdone/hindent/blob/master/atom/hindent.coffee
 - easy invocation: `cat path/to/sourcefile.hs | hindent > outfile.hs`

**Comment by lierdakil** [comment]
Last time I tried hindent, it horribly mangled my files. But if you want to, you can just put path to hindent executable instead of stylish-haskell and it should "just work". This issue is here mostly to remind me about disappointing lack of configurable prettifier invocation parameters (i.e. command line arguments)

**Comment by kRITZCREEK** [comment]
I think HIndent needs the current cursor position though, because it can selectively format declarations.

**Comment by lierdakil** [comment]
@kRITZCREEK, I don't think it does.

**Comment by kRITZCREEK** [comment]
@lierdakil https://github.com/chrisdone/hindent#emacs sounds like it does though. Maybe the emacs plugin is doing something special.

**Comment by lierdakil** [comment]
@kRITZCREEK, from what I could gather reading elisp source, it seems like emacs just feeds source fragments to hindent executable. Not 100% sure on that though, since I'm bad with lisp (all those parentheses make me dizzy surprisingly fast)

**Comment by lierdakil** [comment]
Okay, so rudimentary support is in v1.8.1. Put `hindent` in `stylishHaskellPath` and add desired command line  arguments to `stylishHaskellArguments` (comma-separated, e.g. `--style,gibiansky`).

**Comment by lierdakil** [comment]
Also, this: https://github.com/chrisdone/hindent/blob/master/MIGRATION.md

**Comment by rvion** [comment]
> Also, this: https://github.com/chrisdone/hindent/blob/master/MIGRATION.md

This the reason why I felt free to comment in this issue.
I noticed the change, but IMO, I like this opinionated approach.

**Comment by NewMountain** [comment]
@lierdakil Would it be possible to make a short gist to make this more clear? I use Haskell-IDE and think it is fantastic, but am a bit confused by the instructions. For the sake of total clarity, a quick walk-through would be fantastic. Hindent shows stack installing it in ~/. Do I link to the file or just put the command with params (like 4 indent). I just want to minimize confusion for all interested as much as possible.

**Comment by lierdakil** [comment]
Here's an excerpt from Atom's `config.cson` (Edit→Config...):
```cson
  "ide-haskell":
    stylishHaskellArguments: [
      "--style"
      "johan-tibell"
      "--line-length"
      "88"
    ]
    stylishHaskellPath: "hindent"
```
That is, if `hindent` executable is in PATH (be aware that if you set PATH in rcfile (`.bashrc`/`.zshrc`), it's not picked up by Atom, unless you start it from interactive shell session (terminal)). If not, you can specify full path to it:
```cson
  "ide-haskell":
    # snip...
    stylishHaskellPath: "/home/user/.local/bin/hindent" # or something
```
Note that shell substitutions **won't** work here, i.e. `~` or `$HOME` will be taken verbatim instead of expanding to `/home/user`.

You can use GUI as well:
![image](https://cloud.githubusercontent.com/assets/7275622/18233678/47cd420c-72f6-11e6-9787-5132d441a4aa.png)
`<snip...>`
![image](https://cloud.githubusercontent.com/assets/7275622/18233682/5c4cd314-72f6-11e6-9bf5-ff2cd426cd86.png)

**Comment by NewMountain** [comment]
Perfectly clear now. Thank you so much!

**Comment by moodmosaic** [comment]
Worked like a charm!

**Comment by splodingsocks** [comment]
`hindent` works great for me with version 1.7.2 of ide-haskell, but version 1.8.2 just throws a "Failed to prettify" error when I try to prettify, saying that it exited with a status code of 1.

**Comment by splodingsocks** [comment]
Actually, looks like I had passed in "--indent-size 4" as one argument, instead of separating them with a comma. All works well now. Thanks for the great plugin!
