### ISSUE TITLE
Better show type, show info

### ISSUE THREAD

**Issue by agzam** [atom-haskell/ide-haskell#30]
Would it be possible to implement "Show type" called via keyboard? Or even better - automatically show the type in status bar?

**Comment by lierdakil** [comment]
Check out [haskell-ghc-mod](https://atom.io/packages/haskell-ghc-mod). I've implemented show type and show info via keyboard. Caveat: file needs to be saved for this to work properly, since ghc-mod refuses to read from stdin. Caveat 2: you need latest atom (0.174.0), since they changed API a bit. Caveat 3: you need to disable shadow DOM in atom settings for ide-haskell to work on latest atom (or make some patches)

**Comment by gitfoxi** [comment]
Even better if you could press a key and have it automatically insert the type definition above the selected item.

**Comment by lierdakil** [comment]
Fixed in 0.5.0
