### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by gitfoxi** [atom-haskell/ide-haskell#49]
I wonder if there's any chance for an emacs like REPL?

**Comment by lierdakil** [comment]
Hi there. REPL was originally planned, but repo owner is on hiatus, and I only fix more prominent bugs and accept pull requests for now.

If you're willing to put some time into implementing this feature, I will be happy to review and accept a pull request. Otherwise, I don't really have much time on my hands for the moment.

I reckon this could be implemented via pass-through frontend to `cabal repl`, which should not be too complicated. I only vaguely understand how UI should be implemented though.

**Comment by archaeron** [comment]
I need the same thing for https://github.com/idris-hackers/atom-language-idris/issues/11.

Maybe we could try to find a common solution.

**Comment by lierdakil** [comment]
@archaeron, while I have a pretty good idea on how to implement backend (basic event-driven request-response model on top of ChildProcess pipe would be sufficient, I think), I have a very vague concept of what frontend should look like. Can't really think of anything better than something along the lines of `View` for output and mini-editor for input.

Might want to look at https://github.com/thedaniel/terminal-panel or https://github.com/isis97/atom-terminal-panel for inspiration.

**Comment by archaeron** [comment]
I'll try to implement something for the language-idris package. When I have something that I'm comfortable with I could show it to you and then you can decide if you'd like me to extract it for this package. What do you think?

**Comment by lierdakil** [comment]
I think that this is a rather generous proposition. I am allways glad to have some help on this, so thank you for offering.

**Comment by archaeron** [comment]
There is a screenshot with my simple version here: https://github.com/idris-hackers/atom-language-idris/issues/11

what should a possible API look like?
I think it would be nice to have a good API so that it would be possible to play with the UI without breaking the code

**Comment by archaeron** [comment]
my thoughts:
- single/multi line input
- need to handle autocompletion for the repl
- need to send/recieve from it

**Comment by lierdakil** [comment]
Looks promising!

First order of business is to determine how would you expose your API. From the top of my head, it could be an npm package, apm package, or self-contained source file.

In any case, a couple of basic actions would be "send lines" and "receive lines". Since NodeJS is event-driven, something similar to

```coffeescript
# Event is fired when user sends code lines for execution
# callback = ([line]) ->
# [line] -- array of String
onDidSendLines: (callback) =>
  @emitter.emit 'did-send-lines', callback

# Show lines received from interactive session
# lines = [line] -- array of String
displayLines: (lines) =>
   ...
```

That would require very little "glue" code, and still be flexible enough to handle everything I would care to throw at it (at least I think it will)

I can't say if autocomplete-plus works (or could be coerced to work) for mini-editors, but if not, probably will need something like `setCompletionsFunction: (@getCompletions) =>` with `getCompletions = (prefix) ->`, where `prefix` is String, which would return an array of String with possible completions. If it does though, should probably leverage its API to get consistent look-and-feel across the board.

Single/multiline input could be enabled/disabled by a constructor argument, the rest could be handled by backend receiving `onDidSendLines` event (depending of whether it received single or multiple lines)

Also would be nice to be able to specify grammar for output area view, likely with a constructor argument as well. That would be handy for syntax highlighting.

General utility events and methods, like `close`, `onDidClose`, `show`, `onDidShow`, `destroy`, `onDidDestroy`, etc, can be very handy as well.

That's all literally from the top of my head, so treat it as a source of inspiration, and not an instruction manual.

**Comment by archaeron** [comment]
I'll try something out with your input and come back to you, thank you for the feedback :)
When I have an Idea of how to do the basics I'll sketch out the functions, based on your answer and ask you what you think. Then we can tweak that.

But I don't have too much time in the next few weeks (work/uni), I hope that's okay for you.

**Comment by lierdakil** [comment]
Sure, NP. If I get impatient, I guess I could just start hacking on it myself. But it was on hold for a while now, so a couple more weeks won't change much, I think.

**Comment by archaeron** [comment]
If you become impatient and hack something together I'll probably just "steal" yours (with attribution!) :D

**Comment by lierdakil** [comment]
Sure, that's what MIT license is about, anyway.

**Comment by matthieubulte** [comment]
I just discovered the hydrogen[1] package in the atom blog, and it seems that jupyter[2] has some support for haskell. I haven't tested yet but this could be an option or at least a feature to integrate.

[1] https://atom.io/packages/hydrogen
[2] https://jupyter.org/

**Comment by lierdakil** [comment]
@matthieubulte
Hydrogen seems good, but I have literally no idea how I would "integrate" it. I think it's perfectly fine on its own.

Jupyter isn't really a "REPL", so building a REPL on top of it would be somewhat weird. Plus, haskell platform already has a CLI REPL, which is called `ghci`. Should be possible to interface that directly, with no extra dependencies.

**Comment by lierdakil** [comment]
I've slapped together a prototype: https://github.com/atom-haskell/ide-haskell-repl. It interfaces with `cabal repl`, and *somewhat* works.

This is very early work, and there are some issues with this implementation, so I'm not exactly sure of when or if I will release it, but anyone interested can play around.

**Comment by archaeron** [comment]
very cool!
I'm right now working on mine: https://github.com/idris-hackers/atom-language-idris/pull/80
Maybe we can take inspiration from each other :)

**Comment by lierdakil** [comment]
So, I thought about it, and decided to release somewhat improved prototype: https://atom.io/packages/ide-haskell-repl

Versions 0.0.x are basically prototypes, so things might break.

In any case, please direct any additional feedback to [ide-haskell-repl issue tracker](https://github.com/atom-haskell/ide-haskell-repl/issues)
