### ISSUE TITLE
Failed to spawn command ghc-mod. Make sure ghc-mod is installed and on your PATH

### ISSUE THREAD

**Issue by roelof1967** [atom-haskell/ide-haskell#52]
Hello, 

I have installed ghc-mod and changed the config file to this : 

~ ~ ~ 

"*":
  "exception-reporting":
    userId: "ce46dcf7-b4e1-7b78-0f53-69a2b3d313b9"
  welcome:
    showOnStartup: false
  core:
    {}
  editor:
    invisibles:
      {}

'ide-haskell':
  'ghcModPath': 'home/roelof/cabal/bin/ghcmod'
  'stylishHaskellPath': '/home/roelof/cabal/bin/stylish-haskell'

~ ~ ~ 

but still the above error message
What did I do wrong here ?

Roelof

**Comment by lierdakil** [comment]
First, you missed first `/` in `ghcModPath`. Second, are you sure that it's installed in `$HOME/cabal` and not `$HOME/.cabal`? (notice leading dot)
Please double-check that.

Also bear in mind that there is a known problem on OSX that you need to start `atom` from terminal, otherwise it ignores PATH settings. Not sure if it's applicable here, but try starting from terminal if problem persists.

**Comment by roelof1967** [comment]
I changed it to this : 

~~~ 

"*":
  "exception-reporting":
    userId: "ce46dcf7-b4e1-7b78-0f53-69a2b3d313b9"
  welcome:
    showOnStartup: false
  core:
    {}
  editor:
    invisibles:
      {}

'ide-haskell':
  'ghcModPath': '/home/roelof/.cabal/bin/ghc-mod'
  'stylishHaskellPath': '/home/roelof/.cabal/bin/stylish-haskell'

~~~

but still the same error.

Am working on Debian testing

**Comment by lierdakil** [comment]
Since it's not obvious what is going wrong for you, could you tell what versions of ghc, ghc-mod, and Atom do you use? Note that ide-haskell probably won't work on Atom versions prior to 0.177.0

Please also check if running `/home/roelof/.cabal/bin/ghc-mod` directly from terminal works, just to be sure it's not some esoteric PATH or permissions issue.

**Comment by roelof1967** [comment]
Versions : 

The Glorious Glasgow Haskell Compilation System, version 7.6.3
ghc-mod: master branch 
Atom : 0.199.0

/home/roelof/.cabal/bin/ghc-mod
ghc-mod: No command given (try --help)

Roelof

**Comment by lierdakil** [comment]
Thank you for your patience. It should work with this configuration. Two more things I'd like to check before I start testing with latest ghc-mod.

1. Check if your config.cson is indeed picked up by ide-haskell. Open Edit -> Preferences -> Packages, find ide-haskell, click Settings and check ghc-mod path. Error message seems to suggest that it is not.
2. Try running Atom with modified PATH, e.g. `env PATH=$HOME/.cabal/bin:$PATH atom`

I probably should update readme on configuration, since editing local config is unnecessary with new Atom versions.

**Comment by roelof1967** [comment]
the gch_mod Path is I think not good. It's mentioned Default: ghc-mod

If a changed path, I see no error messages and the path is still default: ghc-mod
and everything is working as expected

**Comment by lierdakil** [comment]
Changing path from settings interface should work (you can punch it in instead of `Default: ghc-mod`). Not sure why editing config.cson didn't work for you, but that's not required nowdays.

**Comment by roelof1967** [comment]
oke, So i have to enter : 

~~~

 $HOME/.cabal/bin/{ghc-mod/stylish_haskell}  ? 

~~~

**Comment by roelof1967** [comment]
Another problem ; when I goto preferences -> Packages -> IDE-haskell and choose for setting I cannot change the path.

**Comment by lierdakil** [comment]
You have to enter
`/home/roelof/.cabal/bin/ghc-mod` into input field for `Ghc-Mod path` and
`/home/roelof/.cabal/bin/stylish-haskell` into input field for `Stylish-Haskell Path`.

Here's an example (please don't forget to change paths according to your setup):
![screen](https://cloud.githubusercontent.com/assets/7275622/7750873/5e1a54cc-ffdf-11e4-905a-cc328b39a4bd.png)

Shell substitutions, like environment variables, don't work here.

**Comment by roelof1967** [comment]
That is what I thougt, But as  I said in my earlier respons, I can click on the fields but no responds on characters or back-space. Can the problem that I try to change it as normal user and not a root ?

**Comment by lierdakil** [comment]
Settings are per-user, so you *don't* want to be root in any case. I have no idea why you can't change those, but this interface is provided by Atom itself, so I can't offer much insight here, besides that it *should* work.

Try removing/renaming  `~/.atom/config.cson` and restarting Atom (note that this will effectively reset Atom configuration to defaults), might be some problem with that. I have no other ideas.

**Comment by roelof1967** [comment]
Thanks, Everything is working well now.
