### ISSUE TITLE
[ghc-mod] ghc-mod doesn't support c-inline (probably not related directly to ide-haskell)

### ISSUE THREAD

**Issue by rvion** [atom-haskell/ide-haskell#64]
![screen shot 2015-05-29 at 08 45 35](https://cloud.githubusercontent.com/assets/2150990/7877791/b4895f3c-05df-11e5-88ab-b943d8deef67.png)

**Comment by rvion** [comment]
It may probably be caused by the lack of cabal file.
inline-c also seems to lack proper cabal repl support.

After some thought, closing this for now.

**Comment by kRITZCREEK** [comment]
This happens, because of speed reasons, checkers compile with -fno-code. Flycheck has the same Problem:

https://github.com/flycheck/flycheck-haskell/issues/6

It's not about C.Inline but rather TemplateHaskell

**Comment by rvion** [comment]
Arf, thanks for the update.
Re-opening in case we can do something about this (config option, ...)

**Comment by rvion** [comment]
I just saw that ghc-mod has been forked in here.
Maybe there is something we can do about TemplateHaskell ? (for pacakge like flycheck/flycheck-haskell#6 or `inline-c`

**Comment by lierdakil** [comment]
That's out of scope for my current work, but sure, when I'm done making `master` ghc-mod play nice with ide-haskell and friends, I might give it a shot.

**Comment by lierdakil** [comment]
Okay, so `Language.C.Inline` is apparently dead or at least on an extended hiatus since basically the start of 2015, and I couldn't convince even the master branch to build on GHC 7.10; besides, TH should work with recent enough versions of ghc-mod most of the time.

Since this isn't the right place for this issue anyway, I'm going to close this now.
