### ISSUE TITLE
Extra folding level at type definition

### ISSUE THREAD

**Issue by neu-rah** [atom-haskell/ide-haskell#72]
Can we have an extra folding level at type declaration, like:

```
maximum' :: (Ord a) => [a] -> a -- << EXTRA FOLDING LEVEL!
maximum' [] = error "maximum of empty list"  
maximum' [x] = x  
maximum' (x:xs) -- << CURRENT FOLDING LEVEL!
    | x > maxTail = x  
    | otherwise = maxTail  
    where maxTail = maximum' xs
--Next line
```

resulting in:

```
maximum' :: (Ord a) => [a] -> a -- << EXTRA FOLDING LEVEL! ...
--Next line
```

**Comment by lierdakil** [comment]
Sorry, Atom folds on indentation only, so this is not possible atm.

**Comment by LukaHorvat** [comment]
Is this possible now? I don't know if things have changed but it seems you can fold whatever you want. It would be great to have the ability to fold away all the implementations but keep all the signatures.

**Comment by lierdakil** [comment]
Well, at least judging by https://github.com/atom/first-mate/issues/48 and https://github.com/atom/atom/issues/11838 nothing's changed. You can create arbitrary folds manually, but AFAIK there's no decent way to do this automagically.

Besides, folding at type signatures is somewhat problematic in itself, since signatures are (a) optional and (b) can be arbitrarily placed. Consider this (admittedly convoluted) example:
```haskell
convertToBase :: Int -> Int -> String
toDec, toHex, toOct :: Int -> String
convertToBase 10 = toDec
convertToBase 16 = toHex
convertToBase 8 = toOct
convertToBase _ = error "not implemented"
toDec = _
toHex = _
toOct = _
```

Folding is going to be rather confusing in this case, don't you think?

**Comment by LukaHorvat** [comment]
Hmm, it still fine to me. Just fold anything at indentation >= 1 UNLESS
it's a part of a type signature. But the comment about having to do it
manually is valid. I just thought that maybe there's a chance that you
already have a list of locations of type signatures somewhere so you could
do something like fold everything at >= 1 and then unfold signatures.
