### ISSUE TITLE
ide-haskell ghc-mod not working

### ISSUE THREAD

**Issue by miguel-negrao** [atom-haskell/ide-haskell#74]
[301:0617/144930:INFO:CONSOLE(241)] "Failed to activate package named 'ide-haskell'", source: /opt/atom/resources/app/src/package.js (241)

ide-haskell: You have selected haskell-ghc-mod as your backend provider, but it does not provide haskell-ide-backend service. You may need to update haskell-ghc-mod. You can disable this message in ide-haskell settings

My haskell environment is setup using nix, I run atom from the terminal after entering a nix-shell. ghc-mod works fine in emacs and in the shell.

ghc 7.8.4
cabal 1.18.0.8
ghc-mod 5.2.1.2
atom v0.181
ide-haskell 1.1.4
haskell-ghc-mod 0.7.7

**Comment by lierdakil** [comment]
Please update Atom.

**Comment by lierdakil** [comment]
Older versions simply don't work due to the fact that API has changed several times since, and there is little reason to try maintaining backwards compatibility, due to the fact that API changes every other release.
This should subside after release of Atom 1.0, but for now you need to update Atom *often*.

**Comment by miguel-negrao** [comment]
I keep forgetting that atom doesn't update itself. After update all is working.
