### ISSUE TITLE
Import local modules

### ISSUE THREAD

**Issue by lucamtudor** [atom-haskell/ide-haskell#76]
When I try to import one of my own modules I get the following error (even though the project compiles and works without problems):
```
Could not find module ‘ModuleName’
Use -v to see a list of the files searched for.
```
Disclaimer, I am a Haskell noob.

**Comment by kRITZCREEK** [comment]
Can you show how your files are laid out? You need to make sure that the .cabal file is at the top level.

Another possibility could be if you've got a library and an executable in the same cabal project you need to depend on the library in your .cabal file.

**Comment by lierdakil** [comment]
Also check if this happens if you run `ghc-mod check Main` manually in project directory (or try path to your Main.hs, if ghc-mod is unable to find Main). If it does, this is definitely a cabal configuration issue. If not, provide details on your setup (file layout, ghc/ghc-mod/Atom versions, etc) and we'll try to figure out what goes wrong.

**Comment by lucamtudor** [comment]
It was a .cabal file issue. As I said, haskell world noob :).
